Implements the `start cvd server` stage.
google/android-cuttlefish pull request #139
Opened 2022-06-22 00:31 UTC by ser-io

2022-06-22 22:03 UTC, jemoreira requested changes

2022-06-23 21:08 UTC, ser-io commented on host/frontend/host-orchestrator/orchestrator/instancemanager.go
> +type LaunchCVDProcedureBuilding interface {
done, used ProcedureBuilder.

2022-06-23 21:08 UTC, ser-io commented on host/frontend/host-orchestrator/orchestrator/instancemanager.go
> +func (m *InstanceManager) completeOperation(opName string, result OperationResult) {
done

2022-06-23 22:37 UTC, ser-io commented on host/frontend/host-orchestrator/orchestrator/instancemanager.go
> +}
created the `ProcedureBuilder` and `Procedure` abstractions to separate building from execution improving this way the testability of the code. now we can have tests checking the order of the stages and the stage instances on the building side, and we can have test for how these are executed.

I also find these design more extensible to new stages as we don't have to change the execution part, just add the new stage to the building part.

2022-06-23 22:42 UTC, jemoreira commented on host/frontend/host-orchestrator/orchestrator/instancemanager.go
> +}
could you be more specific of what you can test now that you couldn't test before? some examples would help

2022-06-23 23:55 UTC, ser-io commented on host/frontend/host-orchestrator/orchestrator/instancemanager.go
> +	return []ProcedureStage{
done

2022-06-24 00:07 UTC, ser-io commented on host/frontend/host-orchestrator/orchestrator/instancemanager.go
> +	LaunchCVDProcedureBuilding LaunchCVDProcedureBuilding
decided to have these fields exported and remove the existing constructor to benefit from the Golang `Composite literals` feature when creating new instances of the IM struct and  in this specific case having these fields exposed does not affect the internals or public contracts of the class.

2022-06-24 00:39 UTC, jemoreira approved these changes

2022-06-29 00:13 UTC, merged