Added env DOCKER_RUNNING=true in Dockerfile
google/android-cuttlefish pull request #491
Opened 2024-03-29 00:03 UTC by WeiChungHsu

To added env DOCKER_RUNNING=true in Dockerfile, and RUN commands could use this var to detect if it is inside the docker container.

2024-03-29 00:15 UTC, 0405ysj approved these changes

2024-03-29 01:11 UTC, ikicha commented
Isn't checking if "/.dockerenv" exist enough?

2024-03-29 01:34 UTC, 0405ysj commented
> Isn't checking if "/.dockerenv" exist enough?

In his experiment, `/.dockerenv` wasn't recognized in `cuttlefish-base.postinst`. That lead `kvm` group being missed.

2024-03-29 03:04 UTC, WeiChungHsu commented
> > Isn't checking if "/.dockerenv" exist enough?
> 
> In his experiment, `/.dockerenv` wasn't recognized in `cuttlefish-base.postinst`. That lead `kvm` group being missed.

Thanks for helping me answer the question. And yes, the `/.dockerenv` is missing when running Dockerfile RUN commands. I search google, stockoverflow and docker sites, this file `/.dockerenv` is not persistent and a good way to check if you are inside docker.

On the other hand, there is no good way and no official suggested solution to detect if you are inside a docker.

2024-03-29 17:03 UTC, jemoreira requested changes

2024-03-29 17:03 UTC, jemoreira commented on docker/arm-server/Dockerfile
> +ENV DOCKER_RUNNING=true
There is code in other places (example: cvd) that checks for the existence of the `.dockerenv` file. It's probably best to make sure it exists here than to come up with another mechanism, something like `RUN touch /.dockerenv` should work.

2024-04-01 18:43 UTC, jemoreira approved these changes

2024-04-01 22:41 UTC, merged