2024-05-16 AOSP merge
google/android-cuttlefish pull request #560
Opened 2024-05-16 22:50 UTC by Databean

2024-05-16 22:56 UTC, jemoreira requested changes

2024-05-16 22:56 UTC, jemoreira commented on base/cvd/cuttlefish/host/commands/cvd/server_command/start.cpp
This file shouldn't be modified on an import from AOSP

2024-05-16 22:56 UTC, jemoreira commented on base/cvd/launch_cvd.proto
This file looks misplaced.

2024-05-16 22:58 UTC, Databean commented on base/cvd/cuttlefish/host/commands/cvd/server_command/start.cpp
`RecursivelyRemoveDirectory` changed signature, it used to return `bool` but now returns `Result<void>`.

2024-05-16 23:10 UTC, Databean commented on base/cvd/launch_cvd.proto
Looks like PR #536 didn't update the merge path for this file.

2024-05-16 23:15 UTC, jemoreira approved these changes

2024-05-17 00:31 UTC, Databean commented
Thanks for reviewing!

2024-05-17 00:32 UTC, merged