Fix permission error on executing chmod for vbmeta images
google/android-cuttlefish pull request #684
Opened 2024-08-19 01:53 UTC by 0405ysj

After previous fix(https://github.com/google/android-cuttlefish/pull/680) is merged, got a similar error on the following step.

```
CVDR_USER_CONFIG_PATH=scripts/docker/cvdr.toml \
./cvdr \
--local_images_zip_src=${HOME}/Downloads/aosp_cf_x86_64_phone-img-12243713.zip \
--local_cvd_host_pkg_src=${HOME}/Downloads/cvd-host_package.tar.gz \
--auto_connect=false \
create
Creating Host........................................ OK
Uploading "cvd-host_package.tar.gz".................. OK
Uploading "aosp_cf_x86_64_phone-img-12243713.zip".... OK
failed to create cvd: api call error 0: failed to launch cvd

DETAILS: failed to launch cvd: chmod /var/lib/cuttlefish-common/user_artifacts/tmp.EsQRqi2xem/vbmeta.img: operation not permitted
```

I followed previous approach applied into `untar` and `unzip` mechanisms in user artifacts. I saw `createUAFile` already does `chmod` things, so I replaced `os.chmod` into `createUAFile`.

2024-08-19 01:58 UTC, 0405ysj commented
Meanwhile, I wonder why our e2e test in https://github.com/google/android-cuttlefish/pull/680 couldn't catch this error.

2024-08-20 23:31 UTC, ser-io requested changes
will be deprecating this create path in HO in favor of environment configurations with user artifacts which already have e2e testing coverage. I'll be sending the relevant `cvdr` fixes to use with this HO version. It's ok to close this PR.

2024-08-21 01:12 UTC, 0405ysj commented
Okay. Could you share us corresponding fix in cloud-android-orchestration github repo when it's ready?

2024-08-21 01:12 UTC, closed without merging

2024-08-21 02:16 UTC, ser-io commented
> Okay. Could you share us corresponding fix in cloud-android-orchestration github repo when it's ready?

Sure, https://github.com/google/cloud-android-orchestration/pull/349