Describe ToT docker image version as head commit short sha
google/android-cuttlefish pull request #705
Opened 2024-09-02 04:34 UTC by 0405ysj

2024-09-02 04:34 UTC, 0405ysj commented on .github/workflows/docker.yaml
> +on: [pull_request, push]
`pull_request` is for testing this workflow. Should be removed before merging this PR.

2024-09-04 01:07 UTC, 0405ysj commented
@ser-io PTAL

2024-09-04 14:27 UTC, ser-io requested changes
Let's move these jobs to the Artifacts workflow https://github.com/google/android-cuttlefish/blob/main/.github/workflows/artifacts.yaml, this way our users can find all our artifacts in the same workflow page.

2024-09-05 03:47 UTC, 0405ysj commented
> Let's move these jobs to the Artifacts workflow https://github.com/google/android-cuttlefish/blob/main/.github/workflows/artifacts.yaml, this way our users can find all our artifacts in the same workflow page.

I'm not still certain with strategies for managing workflows. Though I move docker images into `artifacts.yaml`, we cannot say all our artifacts are in there. For instance, `host-image-ci.yml` uploads lots of host image artifacts to there.

How do you want to manage Github workflow, in overall?

2024-09-05 14:44 UTC, ser-io commented
> > Let's move these jobs to the Artifacts workflow https://github.com/google/android-cuttlefish/blob/main/.github/workflows/artifacts.yaml, this way our users can find all our artifacts in the same workflow page.
> 
> I'm not still certain with strategies for managing workflows. Though I move docker images into `artifacts.yaml`, we cannot say all our artifacts are in there. For instance, `host-image-ci.yml` uploads lots of host image artifacts to there.
> 
> How do you want to manage Github workflow, in overall?

Yes, I missed `host-image-ci.yml` exporting artifacts and didn't act proactively there. I'll work with @WeiChungHsu to have them moved to a single Github workflow, so we can find all of our ToT artifacts on a single page.

2024-09-10 02:12 UTC, 0405ysj commented
> Yes, I missed host-image-ci.yml exporting artifacts and didn't act proactively there. I'll work with @WeiChungHsu to have them moved to a single Github workflow, so we can find all of our ToT artifacts on a single page.

Ack. I updated Github workflow, to build artifacts in `.github/workflows/artifacts.yaml`.

2024-09-10 14:19 UTC, ser-io approved these changes

2024-09-11 01:20 UTC, ikicha approved these changes

2024-09-11 01:32 UTC, 0405ysj commented
@adelva1984 @rmuthiah @Databean @jmacnak @jemoreira Could anyone approve this PR? According to the list of code owners, I think small fix on README.md located at top dir requires additional reviewers. Thanks!

https://github.com/google/android-cuttlefish/blob/main/.github/CODEOWNERS

2024-09-11 01:57 UTC, Databean approved these changes

2024-09-11 01:57 UTC, merged

2024-09-11 01:57 UTC, 0405ysj commented
Thanks!