docker: image-builder.sh: use /usr/bin/env
google/android-cuttlefish pull request #720
Opened 2024-09-10 21:12 UTC by xdevs23

It's more universally supported and makes the script run on NixOS

2024-09-11 01:24 UTC, 0405ysj requested changes
I agree `/usr/bin/env bash` is better than `/bin/bash`, but I prefer to have united shebang between all script files under `docker/`. Could you modify other files as well, such as `image-build-bazel-wrapper.sh` or `guest/run_services.sh`?

Also after your modification, I would recommend you to amend commit with forced push due to our branch maintenance strategy. Thanks for the contribution!

2024-09-12 20:42 UTC, xdevs23 commented
Sure. I force-pushed and also rebased on top of main. There is one change in a C++ file that appears to be generating a script, so make sure that is correct, as I don't have sufficient knowledge about that specific instance to know whether it's correct.

2024-09-13 00:58 UTC, 0405ysj approved these changes

2024-10-14 21:45 UTC, Databean approved these changes

2024-10-14 21:49 UTC, ser-io approved these changes

2024-10-14 22:33 UTC, merged